### ISSUE TITLE
Accessing data with blosc-hdf5-plugin in windows 10

### ISSUE THREAD

**Issue by ashwinlele** [uzh-rpg/DSEC#5]
Hello,

I am trying to access the events data using the blosc-hdf5-plugin package but it is not available for anaconda installed in Windows. Is there any way to access data using the given code in windows? I am getting the following error without it as pointed in another issue-->

Traceback (most recent call last):                                                                                       
 File "<stdin>", line 1, in <module>                                                                                     
File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper                                                   
File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper                                                  
File "C:\Users\Ashwin\anaconda3\envs\optical_flow\lib\site-packages\h5py-2.10.0-py3.6-win-amd64.egg\h5py\_hl\dataset.py", line 573, in __getitem__
         self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)                                                             
File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper                                                   
File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper                                                   
File "h5py\h5d.pyx", line 182, in h5py.h5d.DatasetID.read                                                               
File "h5py\_proxy.pyx", line 130, in h5py._proxy.dset_rw                                                                
File "h5py\_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread                                                          
OSError: Can't read data (can't open directory)        

Thanks in advance!

**Comment by magehrig** [comment]
[This approach](https://github.com/h5py/h5py/issues/611#issuecomment-353694301) is a quick hack that might work for you. Otherwise, you have to build blosc-hdf5-plugin yourself.

**Comment by ashwinlele** [comment]
Thank you. This worked for me.
